version: '3.8'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    networks:
      - web_network
    environment:
      DOMAINS: 'uprun.upfg.net -> http://uprun_nginx:80, takaha.si -> http://tak_nginx:80, thethirdofmay.jp -> http://tak_nginx:80'
      STAGE: 'production'
      CLIENT_MAX_BODY_SIZE: 100M
      HSTS_MAX_AGE: 120
    volumes:
      - https-portal-data:/var/lib/https-portal
    restart: always
    depends_on:
      tak_nginx:
        condition: service_started
      uprun_nginx:
        condition: service_started
      
volumes:
  https-portal-data:

networks:
  web_network:
    external: true
