version: '3.8'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    networks:
      - web_network
    environment:
      DOMAINS: 'uprun.upfg.net -> http://uprun_nginx:80'
      STAGE: 'production'
    volumes:
      - https-portal-data:/var/lib/https-portal
      
volumes:
  https-portal-data:

networks:
  web_network:
    external: true
